### ISSUE TITLE
The strange batch_size setting

### ISSUE THREAD

**Issue by FunkyKoki** [cvlab-yonsei/dkn#4]
When I try to reproduce the results on NYU dataset. I found that the training batch_size is set to one.
When I did the 4x SR task on NYU, I tried another batch_size because the original settings cannot help me get `1.62` told from the paper.
Is there some trick to reproduce the results using DKN? Below are the comparison. 

![image](https://user-images.githubusercontent.com/36239710/113960592-4872ec80-9857-11eb-978f-e8fee2b96846.png)

**Comment by TZYSJTU** [comment]
Well, after a month's study, I finnaly got the mistake point of the experiment.

It starts with the unmatched BIcubic upsampling baseline result:
I found this because when I use Bicubic to downsample then use Bicubic to upsample resulting in much better RMSE 8.07 than 14.22 (8x upsampling)
In the dataloader file, the authers use Bicubic to downsample the HR depth map to obtain LR input.
target = np.array(Image.fromarray(depth).resize((w//s,h//s),Image.BICUBIC).resize((w, h), Image.BICUBIC))

However, all other papers use nearest neighbor downsampling on NYU v2. See CVPR paper "Pixel-Adaptive Convolutional Neural Networks" for evidence.
This means the comparison is unfair.
Therefore, all the experiment results should be re-trained with:
target = np.array(Image.fromarray(depth).resize((w//s,h//s),Image.NEAREST).resize((w, h), Image.BICUBIC))

**Comment by jun0kim** [comment]
Not sure why this happen. 
The version of PyTorch may occur this kind of problem. 
Please check the version.

**Comment by xuhuiling999** [comment]
> When I try to reproduce the results on NYU dataset. I found that the training batch_size is set to one. When I did the 4x SR task on NYU, I tried another batch_size because the original settings cannot help me get `1.62` told from the paper. Is there some trick to reproduce the results using DKN? Below are the comparison.
> 
> ![image](https://user-images.githubusercontent.com/36239710/113960592-4872ec80-9857-11eb-978f-e8fee2b96846.png)

你好，我最近也在从事这个方向的研究，准备复现这篇论文的结果，之前我是使用的自己提取的nyu数据集，但是似乎要用16位的深度图，我之前使用的是8位的深度图，所以无法成功复现结果。作者提供的似乎是16位深度图，但是我无法成功下载，若你成功下载了作者提供的nyu_slipt数据集能否分享一下？我的邮箱是1435303243@qq.com。
